# Generated by Django 3.1.6 on 2021-02-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketfile',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
