# Generated by Django 3.1.6 on 2021-02-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_bucket_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
