# Generated by Django 3.1.6 on 2021-02-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0004_bucket_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='has_password',
            field=models.BooleanField(default=False),
        ),
    ]
