# Generated by Django 3.1.6 on 2021-02-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0005_bucket_has_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
