# Generated by Django 3.1.6 on 2021-02-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0006_auto_20210220_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketfile',
            name='verbose_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
