# Generated by Django 3.1.6 on 2021-02-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0007_bucketfile_verbose_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketfile',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
