# Generated by Django 3.1.6 on 2021-02-21 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0009_auto_20210221_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketfile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
